version: '3.2'


services:
  auth-service:
    build: AuthService/
    container_name: 'AuthServiceApp'
    ports:
      - '8080:8080'
  account-service:
    build: AccountService/
    container_name: 'AccountServiceApp'
    depends_on:
      - auth-service
    ports:
      - '8081:8081'
  external-payment-system:
    build: ExternalPaymentSystem/
    container_name: 'ExternalPaymentSystemApp'
    depends_on:
      - account-service
    ports:
      - '8082:8082'

